--- 
- name: Install filebeat
  hosts: all
  become: yes
  become_user: root
  tasks:
    - block:
      - name: Install filebeat repo on centos 6
        package: 
          name: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.1.1-x86_64.rpm
      - name: install from rpm
        state: latest
        notify: FILEBEAT_CENTOS_6
      when: ansible_distribution == "Centos" and ansible +distribution_major_version =="6"
      ignore_errors: true
    


    - block:
      - name: Install filebeat repo on centos 7
        packa:
          name:  curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.1.1-x86_64.rpm
          state: latest
        notify: FILEBEAT_CENTOS_7
      when: ansible_distribution == "Centos" and ansible +distribution_major_version =="7"
      ignore_errors: true
      


  handlers: 
    - name: FILEBEAT_CENTOS_6
      services:
        name: filebeat
        status: restarted
    - name: FILEBEAT_CENTOS_7
      services:
        name: filebeat
        status: restarted