--- 
- name: Install filebeat
  hosts: all
  become: yes
  become_user: root
  tasks:
    - block:
      - name: Install filebeat repo on centos 6
        shell: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.1.1-x86_64.rpm
      - name: install from rpm
        shell: rpm -vi filebeat-7.1.1-x86_64.rpm
        notify: FILEBEAT_CENTOS_6
      when: ansible_distribution == "Centos" and ansible +distribution_major_version =="6"
    


    - block:
      - name: Install filebeat repo on centos 7
        shell: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.1.1-x86_64.rpm
      - name: install from rpm
        shell: rpm -vi filebeat-7.1.1-x86_64.rpm
        notify: FILEBEAT_CENTOS_7
      when: ansible_distribution == "Centos" and ansible +distribution_major_version =="7"
      


  handlers: 
    - name: FILEBEAT_CENTOS_6
      services:
        name: filebeat
        status: restarted
    - name: FILEBEAT_CENTOS_7
      services:
        name: filebeat
        status: restarted