---
- name: Installs wordpress
  hosts: Instance
  become: yes
  become_method: sudo
  tasks:
    - name: Install necessary packages
      package:
        name: "{{item}}"
        state: latest
      with_items:
       - wget 
       - unzip
       - httpd  
       - php
       - php-gd
       - mysql
       - mariadb-server
       - php-mysql
       - php-fpm
      ignore_errors: true

  
    - name: Install epel-release
      shell: "sudo wget -q http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    - name: config manager enabled 
      shell: "sudo yum-config-manager --enable remi-php70"
    - name : update httpd PHP 
      shell: "sudo yum update httpd php php-mysql mysql" 

    - name: Download wordpress Package
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/

    - name: Unzip wordpres file
      unarchive:
        src: "/tmp/wordpress-5.2.1.tar.gz"    
        dest: "/var/www/html"
        remote_src: yes
      become: yes
      become_method: sudo

    - name: Move files to html folder
      shell: "mv /var/www/html/wordpress/* /var/www/html"
      become: yes
      become_method: sudo
      ignore_errors: yes

    - name: Restart httpd
      systemd:
        name: httpd
        state: restarted  
        enabled: yes
      become: yes
      become_method: sudo